# This workflow will execute xl cli apply on newly created or updated yaml files. 

name: demo yaml file
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  run_xl_apply:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout release-content Repository
        uses: actions/checkout@v3

      - name: Pull Release Docker image
        run: docker pull xebialabsunsupported/xl-release:${{ vars.DAI_RELEASE_24_3 }}

      - name: Run Docker container
        run:  | 
          docker run -p 5516:5516 -d --name xlr${{ vars.DAI_RELEASE_24_3 }} -e "ACCEPT_EULA=Y"  xebialabsunsupported/xl-release:${{ vars.DAI_RELEASE_24_3 }}
          sleep 100
              
      - name: Download and Install xl-cli
        run: |
         wget https://dist.xebialabs.com/public/xl-cli/${{ vars.DAI_RELEASE_XL_CLI_LATEST }}/linux-amd64//xl -O xl1
         chmod 755 xl1
         ./xl1 version
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v43
        
      - name: Apply yaml files to check if xl-apply works
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
            if [[ "$file" == *.yaml || "$file" == *.yml ]]; then
               echo "$file is yaml file"
               ./xl1 apply -f $file
            fi
          done
        
