name: Get Target Branch Name

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  get_target_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Target Branch Name
        run: echo "TARGET_BRANCH=${{ github.event.pull_request.base.ref }}" >> $GITHUB_ENV

      - name: Print Target Branch Name
        run: echo "Target branch is $TARGET_BRANCH"

      - name: Get version name from version.json
        run: |
          VAR_FILE=".github/config/version.json"
          if [ -f "$VAR_FILE" ]; then
              echo "json file is $VAR_FILE"
              echo "target branch is $TARGET_BRANCH"
              product_version=$(jq -r --arg branch "$TARGET_BRANCH" '.[$branch]' "$VAR_FILE")
              echo "Product version: $product_version"
              echo "product_version=$product_version" >> $GITHUB_ENV
          else
            echo "File $VAR_FILE does not exist"
          fi
          echo "Debug: product_version=$product_version"
      - name: Print version got from json
        run: echo "xl-cli and docker version from josn file is $product_version"
